[build]
rustflags = ["--cfg=web_sys_unstable_apis"]

[alias]
elodin = "run --bin elodin"
elodin-db = "run --bin elodin-db"
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/elodin-sys/bbq2.git?rev=b6e36706a5549d770ebf2dc122b39cef1368b06d"]
git = "https://github.com/elodin-sys/bbq2.git"
rev = "b6e36706a5549d770ebf2dc122b39cef1368b06d"
replace-with = "vendored-sources"

[source."git+https://github.com/elodin-sys/big_space.git?branch=no_prop_rot_v0.16"]
git = "https://github.com/elodin-sys/big_space.git"
branch = "no_prop_rot_v0.16"
replace-with = "vendored-sources"

[source."git+https://github.com/elodin-sys/nodit.git?rev=cd284cd0f16d475786dae8629cebda4e14177ee1"]
git = "https://github.com/elodin-sys/nodit.git"
rev = "cd284cd0f16d475786dae8629cebda4e14177ee1"
replace-with = "vendored-sources"

[source."git+https://github.com/shanecelis/bevy_editor_cam.git?branch=feat/system-set-0.6.0"]
git = "https://github.com/shanecelis/bevy_editor_cam.git"
branch = "feat/system-set-0.6.0"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "../vendor-elodin"
